# Generated by Django 4.2.2 on 2023-06-26 08:52

import core.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLogsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('code', models.CharField(default=core.utils.randcode_gen, max_length=100, verbose_name='CODE')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('driver_name', models.CharField(max_length=250, verbose_name='FULL NAME')),
                ('vehicule_type', models.CharField(max_length=150, verbose_name='VEHICULE TYPE')),
                ('time_in', models.CharField(max_length=50, verbose_name='TIME IN')),
                ('time_out', models.CharField(max_length=50, verbose_name='TIME OUT')),
                ('km_in', models.CharField(max_length=50, verbose_name='KM IN')),
                ('km_out', models.CharField(max_length=50, verbose_name='KM OUT')),
                ('destination', models.CharField(max_length=500, verbose_name='DESTINATION')),
                ('voucher_number', models.CharField(max_length=500, verbose_name='VOUCHER NUMBER')),
                ('cost', models.CharField(max_length=500, verbose_name='COST')),
                ('note', models.CharField(max_length=500, verbose_name='NOTE')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
