# Generated by Django 4.2.2 on 2023-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlogsheet',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='NOTE'),
        ),
    ]
